spring:
  data:
    mongodb:
      uri: mongodb+srv://mongo:i4T4gIm7XPSvFYfV@dev-gdgochack25-mongodb.u214z.mongodb.net/test?retryWrites=true&w=majority

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gcp:
      credentials:
        location: classpath:stt.json

logging:
  level:
    org.springframework.cache: trace
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.mongodb: DEBUG
