spring:
  data:
    mongodb:
      uri: mongodb+srv://mongo:i4T4gIm7XPSvFYfV@dev-gdgochack25-mongodb.u214z.mongodb.net/test?retryWrites=true&w=majority

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cloud:
    gcp:
      credentials:
        location: classpath:stt.json

openai:
  model: gpt-4o
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
logging:
  level:
    org.springframework.cache: trace
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.mongodb: DEBUG

secret:
  jwt-secret-key: 6ce1d11af9ac1adf97712c069ca33bc4564d675ce3958942bb3dc5601829881430cfd8d98c87452ae5b098d80874df8ca569c03fa79191b4ae755e86fd719347
  accessToken-valid-time: 1800000
  refreshToken-valid-time: 604800000
